version: "3.7"

services: 
  nginx_bodega:
    platform: linux/x86_64
    image: nginx:stable-alpine
    container_name: nginx_bodega
    ports:
      - 8001:81
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bodega
      - mysql_bodega
    networks:
      - laravel

  mysql_bodega:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql_bodega
    restart: unless-stopped
    tty: true
    ports: 
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'bodega'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret.root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_bodega
    networks:
      - laravel

  bodega:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bodega
    volumes:
      - .:/var/www/html 
    networks:
      - laravel

networks:
  laravel: