version: "3.7"

services: 
  nginx_cocina:
    platform: linux/x86_64
    image: nginx:stable-alpine
    container_name: nginx_cocina
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cocina
      - mysql_cocina
    networks:
      - laravel

  mysql_cocina:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql_cocina
    restart: unless-stopped
    tty: true
    ports: 
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret.root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_cocina
    networks:
      - laravel

  cocina:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocina
    volumes:
      - .:/var/www/html 
    ports:
      - 9000:80
    networks:
      - laravel

networks:
  laravel: